server:
  port: 8000

spring:
  application:
    name: api-gateway
  config:
    activate:
      on-profile: local
    import:
      - security/application-local.yml

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: true